### ISSUE TITLE
read SNP data

### ISSUE THREAD

**Issue by strei102** [QTCAT/qtcat#13]
Hi Jonas,

I tried to use your script but I have a problem with the read.SNPdata function. When I try to read my SNP file I get the following error "Error in read_snpData(file, sep, quote, rowNames, na.string, nrows) : 
  unused argument (nrows)". 
The command which I use is "snp <- read.snpData("SNPdata_2017vcf.csv", sep = ","). Even if I add the whole path I get this error. It would be great if you have any advice to solve my problems.
Regards,
Stephan

**Comment by jrklasen** [comment]
can you provide me with a small reproducible example, otherwise it's hard to guess what's going wrong

**Comment by strei102** [comment]
I sent you an email with a google drive link where you can find a small dataset.

**Comment by jrklasen** [comment]
strange, haven't gotten your email, can you resent it to qtcat"at"gmx.de

**Comment by strei102** [comment]
I've sent it again to qtcat"at"gmx.de. I think something went wrong the first time. I hope it is working now.

**Comment by jrklasen** [comment]
i cant reproduce the error

```
library("qtcat")
snp <- read.snpData("~/Downloads/SNP_2017_trimmed2.csv", sep = ",")
```
works for me

**Comment by jrklasen** [comment]
can you start a new R console and check if it works there for you to?

**Comment by strei102** [comment]
Oh man, I am so dumb. It's working now. I don't now what went wrong but it works. Thanks a lot.
