### ISSUE TITLE
Plot with overlaps and chromosomes are missing

### ISSUE THREAD

**Issue by strei102** [QTCAT/qtcat#14]
I ran qtcat and plotted the QTC's as well as the sel freq. I didn't get any error massage but the plots I show chromosome overlaps and some chromosomes are missing. I think that is not how it supposed to be. It would be great if you can help me.

Cheers, Stephan

**Comment by jrklasen** [comment]
That seems to be a bug. Can you give me access to your results? You can save them as follows:

```
fitted <- qtcatHit(pheno, geno)
save(fitted, file = "fitted.rdat")
```

**Comment by jrklasen** [comment]
bug should be fixed now
