### ISSUE TITLE
Effect sizes and variance explained.

### ISSUE THREAD

**Issue by jostego** [QTCAT/qtcat#15]
I have some results from a QTCAT analysis, but I can't find a way to extract effect sizes and variance explained for the reported hits. Can you please point me in the right direction @jrklasen?

**Comment by jrklasen** [comment]
It is possible to run a linear model at the output of QTCAT. This gives you the effects for each cluster medoid and if your model has no additional covariates (e.g. experiment, environment, ...), R^2 is the explained variance. See the example:

```R
require(qtcat)

pfile <- system.file("extdata/phenodata.csv", package = "qtcat")
gfile <- system.file("extdata/snpdata.csv", package = "qtcat")
pdat <- read.csv(pfile, header = TRUE)
snp <- read.snpData(gfile, sep = ",")
clust <- qtcatClust(snp)
geno <- qtcatGeno(snp, clust)
pheno <- qtcatPheno(names = pdat[, 1],
                    pheno = pdat[, 2])
fitted <- qtcatHit(pheno, geno)

fitted2 <- lmQtc(fitted, pheno, geno)
summary(fitted2)
```

**Comment by jostego** [comment]
Thank you. So, if I have covariates, it's not possible to extract the variance explained only by the cluster medoids?

**Comment by jrklasen** [comment]
It is possible, but not implemented. You could use the code of `lmQtc` and replace the linear model with a linear mixed model (`lme4` could be used) according to your needs.  A mixed model is needed to estimate variance components for covariates, QTC-medoids, and residuals.

https://github.com/QTCAT/qtcat/blob/73947896fb9e0806b9a25036796fab02bb2bf18b/R/associationTest.R#L355

**Comment by jostego** [comment]
Great. Thanks again.
