### ISSUE TITLE
visualisation functions

### ISSUE THREAD

**Issue by nstjhp** [QTCAT/qtcat#4]
Hey, Is it possible for you to provide functions for visualising the various qtcat outputs? (I saw the talk from Korbinian a couple of times so you must have some code to do this e.g. the figure of the root meristem data).

I was quickly able to plot the dendrogram from the clustering output, and also do a -log10(p-values) plot, both for the small example dataset, but it would be nice to know how to link these to the relevant chromosome/position etc. 

Do you have any plans to include functions for producing plots in the package?

**Comment by jrklasen** [comment]
Hi @nstjhp, so far I have plotting functionality only in scripts, but you are right I will clean it up and integrate functions in to the package.

**Comment by nstjhp** [comment]
Thanks that's good to hear. I have allocated some to time to playing with qtcat next week so would be really great to have the idea of how to properly get your objects into a plot I can show.
