### ISSUE TITLE
How to handle ambiguity codes (and other queries)

### ISSUE THREAD

**Issue by nstjhp** [QTCAT/qtcat#7]
Hi Jonas, in the real data set we were testing qtcat on yesterday we found a few problems that I do not know how to handle.

1. 
We have a great deal of ambiguity codes (K,R,M,Y etc.) called throughout the data in many different lines and marker positions - can the method behind qtcat adapt to when you don't just have ACGT?

2. 
Before this though we had to exclude about 80% of the data due to missing marker data - I see you have a PR on this - is that branch suitable for testing?

3. 
Even after cleaning up the data to only get complete cases with no ambiguity codes (down to 0.2% of our original data!) we had a couple of markers where there were 3 possible alleles across the lines - I also wonder if this can be handled at some point? I show an example below:

I made a tiny file (call it tmp.csv) to check that this was really the case and also found the warning message is slightly incorrect. 
```
Chromosome,Positions,Indiv1,Indiv2,Indiv3,Indiv4
1,10,AA,CC,CC,GT
1,420,AA,CC,GT,AA
1,804,AA,AA,AG,AA
1,942,AG,AA,GG,AG
1,1122,CG,CG,CG,AA
1,2434,TT,TT,CT,CT
```

```
R> read.snpData("tmp.csv",sep = ",")
warning: Line 2 has more or less than two alleles and therefore the line is skipt
warning: Line 2 has more or less than two alleles and therefore the line is skipt
warning: Line 4 has more or less than two alleles and therefore the line is skipt
```

I think it should be lines 1,2 and 5 that are skipped based on what goes into the position slot of snpData.

Thank you for your time

**Comment by jrklasen** [comment]
Hi Nick

1. For a association method ambiguity is similar to missing data, as two lines sharing at one position e.g. R can in fact have different alleles (different effect at the phenotype). Maybe there is a imputing method for this specific data type?

2. I'm working at a simple imputing method for NAs, using the clustering information, but it is not ready for use yet. So far you have to impute your data outside of QTCAT.

3. Tripletons require that on SNP is represented in two columns of the design matrix, which is a tricky to implement into the HIT algorithm used in QTCAT. Therefore it will not be implemented any soon.

I have fixed the line counting in the warning message.

**Comment by nstjhp** [comment]
Hi Jonas I've not had any luck finding anything seemingly suitable for imputation of the ambiguity codes but perhaps you can also recommend your preferred software for imputation of missing data? When we tried with TASSEL we got a numerical matrix but not with ACGT in.

Also I tried running QTCAT on some Arabidopsis data and noted that it's not deterministic i.e. I'm getting different results through different runs - have you quantified this variability of your method, and what do you recommend for handling this? Is it suitable to do many iterations and pick the most frequently occurring SNPs as likely true candidates, or go by most significant p-value over many runs?

**Comment by jrklasen** [comment]
I'm not really experienced with imputation tools, sorry. QTCATs ``read.snpData`` function is not yet as general as I would like it to be. However, it is not necessary that the alleles are coded ACTG, e.g. a locus can not only be coded  by AA, AT, TT, ... you could also use AA, AB, BB or 00, 01, 11 ... Furthermore there is a ``as.snpData`` function, which can be used for numeric matrices.

The HIT algorithm is a re-sampling algorithm, ``qtcatHit`` is using 50 sample splits by default (argument ``B``). The results should not vary that much, only QTCs which are just reaching the threshold in one run, can be missed in another. If the results are really unstable this is a indication for a model miss-specification, e.g. missing environmental effect or strong epistasis.  For this situation there is no easy and/or general advise (which this is equally true for other tools of course).

**Comment by nstjhp** [comment]
Thanks for the info I'll take a look at the `as.snpData` as that sounds potentially promising for what we can get out of other programs.

If that is how it works then I will probably try increasing `B` to be more sure of which are the true candidates. I ran the default qtcat over the dataset 5 times and different SNPs were pulled out 1-5 times which is why I was a little concerned. Certainly the ones that came up in every run seem to be good candidates to move forward with. And the number of clusters between runs similarly varied e.g. between 6 and 13 clusters sometimes using the same data. What is controlling the threshold you referred to? It seems it could be useful to check how far above it the various QTCs are.

Also, to learn more about the method (and maybe save so many queries), could you please give me an indication of when the paper might be out? I can email you if you prefer that to be kept private.

**Comment by jrklasen** [comment]
I meant the alpha level. The algorithm can be found hear : https://github.com/QTCAT/hit. The readme is liking to the key publication.
